permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author:
  name: Wresle.Wu
  email: wsxinchina@gmail.com
  weibo: http://www.weibo.cn/u/2176268011
  github: http://github.com/wrestle

# 站点信息
title: WuShxin's Blog
description: 维斯特的博客

# gavatar头像及Favicon
gavata : http://g1.680.com/2014-01/201401140910543498.jpg
favicon: /public/img/geek.jpg

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: wrestle

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates:
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
